### ISSUE TITLE
Notification's sound doesn't work on crdroid

### ISSUE THREAD

**Issue by LordArrin** [bigsaltyfishes/device_lenovo_J607F#10]
Music, video, other sounds works normal.

**Comment by bigsaltyfishes** [comment]
Is this happened on all kinds of playback device? Or just happened on specific device?

**Comment by LordArrin** [comment]
Didn't check it, sorry, but my friend had same problem on your's arrow build.

**Comment by bigsaltyfishes** [comment]
I've checked issue. Will try to fix it.

**Comment by LordArrin** [comment]
Can send any logs, if needed.

**Comment by bigsaltyfishes** [comment]
Will fix on next build.

**Comment by bigsaltyfishes** [comment]
Also, is alarm working fine? I've noticed that low-latency-playback is not working. This should also affect alarm.

**Comment by LordArrin** [comment]
Now i check timer on google clock, it isn't work.

**Comment by LordArrin** [comment]
Download your fixed policy, it works. Good work, thanks.
