### ISSUE TITLE
詢問其他反饋或是提問的管道

### ISSUE THREAD

**Issue by skysumbra** [bigsaltyfishes/device_lenovo_J607F#11]
你好
在你的原本發文的地方無法進行回覆，想請問是否有你的QQ(群)或是TG(群) 可以直接尋問？
會注意詢問，你在這平台上閱讀使用率應該會高些，請問可以嗎？

**Comment by skysumbra** [comment]
我目前也有一台linux pc ，或許也可以幫忙build ，但是相關的環境與設定想請教下

**Comment by bigsaltyfishes** [comment]
> 你好
> 在你的原本發文的地方無法進行回覆，想請問是否有你的QQ(群)或是TG(群) 可以直接尋問？
> 會注意詢問，你在這平台上閱讀使用率應該會高些，請問可以嗎？

关于这个的话，目前我是没有这类群组的

**Comment by bigsaltyfishes** [comment]
> 我目前也有一台linux pc ，或許也可以幫忙build ，但是相關的環境與設定想請教下

相关的环境的话，我使用的是 Arch Linux Rolling, 直接从 AUR 安装 lineageos-devel 软件包就可以了，如果是 Ubuntu 20.04 的话， 可以参考这里 https://github.com/Miku-UI/manifesto/blob/snowland/READMECN.md

**Comment by skysumbra** [comment]
> > 我目前也有一台linux pc ，或許也可以幫忙build ，但是相關的環境與設定想請教下
> 
> 相关的环境的话，我使用的是 Arch Linux Rolling, 直接从 AUR 安装 lineageos-devel 软件包就可以了，如果是 Ubuntu 20.04 的话， 可以参考这里 https://github.com/Miku-UI/manifesto/blob/snowland/READMECN.md

我之前找了一下，我那台linux pc 只有32GB，
之後在找台PC 試試
