### ISSUE TITLE
[詢問] 請問你的pad plus 有沒有備份未修改的boot 和vbmeta

### ISSUE THREAD

**Issue by skysumbra** [bigsaltyfishes/device_lenovo_J607F#12]
你好
想請問你的pad plus 有沒有備份未修改的boot 和vbmeta
目前系統最新的版本號為13.1.470 ST
或是有知道哪裡有人有留一份
謝謝

**Comment by bigsaltyfishes** [comment]
没有，我只有 13.0.234 的备份

**Comment by skysumbra** [comment]
> 没有，我只有 13.0.234 的备份

請問你考慮更新嗎？

**Comment by bigsaltyfishes** [comment]
> > 没有，我只有 13.0.234 的备份
> 
> 請問你考慮更新嗎？

不考虑更新，目前我适配的类原生都是使用基于CAF Tag的内核源码构建，并不打算使用Prebuilt kernel
