### ISSUE TITLE
Iptables

### ISSUE THREAD

**Issue by LordArrin** [bigsaltyfishes/device_lenovo_J607F#13]
Hi man! Can you add support for iptables? It's very important for Russian mobile operators) Thanks.

**Comment by bigsaltyfishes** [comment]
AOSP had removed iptables from system and use eBPF firewall instead, and iptables can't be restore in any meaningful way. I'm not sure why it's important for you. I won't fix it as it is AOSP side changes, that's a hard work, and will break something important.
For detail, see https://lineageos.org/Changelog-26/

**Comment by LordArrin** [comment]
Alright, dont hear about that, man.
