### ISSUE TITLE
Bug：arrow 13的蓝牙音频是坏的

### ISSUE THREAD

**Issue by jerry3055** [bigsaltyfishes/device_lenovo_J607F#14]
连接蓝牙耳机后，声音输出仍然是扬声器。

**Comment by bigsaltyfishes** [comment]
是自己构建的还是刷我的包？如果是我的包的话是vanilla还是gapps？

**Comment by jerry3055** [comment]
> 是自己构建的还是刷我的包？如果是我的包的话是vanilla还是gapps？

你的包，vanilla版

**Comment by bigsaltyfishes** [comment]
> > 是自己构建的还是刷我的包？如果是我的包的话是vanilla还是gapps？
> 
> 你的包，vanilla版

问题这边已经确认了，修复以后我再发布更新

**Comment by bigsaltyfishes** [comment]
问题目前已经解决，稍后会在同一链接发布更新

**Comment by jerry3055** [comment]
> 问题目前已经解决，稍后会在同一链接发布更新

好的，感谢。
