### ISSUE TITLE
再提个关于WiFi的问题，修不修看大佬您的心情

### ISSUE THREAD

**Issue by jerry3055** [bigsaltyfishes/device_lenovo_J607F#7]
经过我的测试，发现这货似乎不支持2.4GWiFi下的12和13信道，如果AP处于这俩信道，平板会直接检测不到。

我知道有信道有地区差异，但不确定是不是硬件本身的问题（我觉得不是，doge），还是内核的驱动问题。

**Comment by bigsaltyfishes** [comment]
我手头里都设备都是最高只能支持到11信道的，现在没有办法去确认问题，这个问题现在只能先搁置一下了
![IMG_20220518_213056.jpg](https://user-images.githubusercontent.com/15278036/169051268-dc4c7c09-5553-4ba3-b7dc-620556276063.jpg)

**Comment by jerry3055** [comment]
> 我手头里都设备都是最高只能支持到11信道的，现在没有办法去确认问题，这个问题现在只能先搁置一下了 ![IMG_20220518_213056.jpg](https://user-images.githubusercontent.com/15278036/169051268-dc4c7c09-5553-4ba3-b7dc-620556276063.jpg)

没事，问题不大，这不是个致命的问题，毕竟改AP的信道比改驱动简单（doge）
