### ISSUE TITLE
如果要對Arrowos系統反饋要在哪裡才好？

### ISSUE THREAD

**Issue by skysumbra** [bigsaltyfishes/device_lenovo_J607F#8]
你好，由於你的原本的地方操作有其困難，請問哪裡可以反饋？
或是系統就是那樣了不會在更新了？
謝謝

**Comment by bigsaltyfishes** [comment]
可以考虑在xda的帖子下面反馈，由于没有专门编译服务器，对于复数系统的更新会有困难，现在我正在适配一些别的系统，最后可能会挑出一个来长期维护

**Comment by skysumbra** [comment]
使用 Lenovo Xiaoxin Pad Plus  搜尋沒有找到相關的版塊，
請問是在那一個版塊裡面？
謝謝

**Comment by bigsaltyfishes** [comment]
联想小新 Pad Plus 的国际版型号是 Lenovo P11 5G, 相应的帖子也在 Lenovo P11 板块下

**Comment by skysumbra** [comment]
找到了，謝謝
https://forum.xda-developers.com/t/rom-unofficial-12-1-0-tb-j607f-arrowos-12-1.4443825/
